
[package]
publish = false
name = "oveo-optimizer"
version = "0.0.1"
authors = ["Boris Kaul <localvoid@gmail.com>"]
edition = "2024"
license = "MIT"
homepage = "https://github.com/localvoid/oveo"
repository = "https://github.com/localvoid/oveo"
description = "oveo javascript optimizer NAPI bindings"

[lib]
crate-type = ["cdylib"]

[dependencies]
regex.workspace = true
napi.workspace = true
napi-derive.workspace = true
oveo.workspace = true

[build-dependencies]
napi-build.workspace = true

[lints]
workspace = true
