/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Optimizer {
  constructor(options?: OptimizerOptions | undefined | null)
  importExterns(data: Uint8Array): void
  importPropertyMap(data: Uint8Array): void
  exportPropertyMap(): Uint8Array
  optimizeModule(sourceText: string): Promise<OptimizerOutput>
  optimizeChunk(sourceText: string): Promise<OptimizerOutput>
}

export declare class OptimizerOutput {
  code: string
  map: string
}

export interface OptimizerOptions {
  hoist?: boolean
  dedupe?: boolean
  hoistGlobals?: boolean
  inlineExternValues?: boolean
  singletons?: boolean
  renameProperties?: RenamePropertiesOptions
}

export interface RenamePropertiesOptions {
  pattern?: string
}
