/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Optimizer {
  constructor(options?: OptimizerOptions | undefined | null)
  importExterns(data: Uint8Array): void
  importPropertyMap(data: Uint8Array): void
  updatePropertyMap(): Uint8Array | null
  transform(sourceText: string, moduleType: string): Promise<OptimizerOutput>
  renderChunk(sourceText: string): Promise<OptimizerOutput>
}

export declare class OptimizerOutput {
  code: string
  map: string
}

export interface ExternsOptions {
  inlineConstValues?: boolean
}

export interface GlobalsOptions {
  include?: Array<string>
  hoist?: boolean
  singletons?: boolean
}

export interface OptimizerOptions {
  hoist?: boolean
  dedupe?: boolean
  globals?: GlobalsOptions
  externs?: ExternsOptions
  renameProperties?: RenamePropertiesOptions
  url?: URLOptions
}

export interface RenamePropertiesOptions {
  pattern?: string
}

export interface UrlOptions {
  baseURL: string
}
